# Generated by Django 3.2.5 on 2021-07-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStocks',
            new_name='countInStock',
        ),
    ]
