products = [
    {
        '_id': '1',
        'name': 'Oraimo Freepods',
        'image': './images/oraimo-0.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Oraimo Riff 2',
        'image': '/images/oraimo-1.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'Oraimo Rhyme',
        'image': '/images/oraimo-2.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Oraimo Airbuds',
        'image': '/images/oraimo-3.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '6',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 0,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
    {
        '_id': '8',
        'name': 'Oraimo Freepods',
        'image': '/images/oraimo.jpg',
        'description': 'Bluetooth earbuds',
        'brand': 'Oraimo',
        'category': 'Electronics',
        'price': '2799.00',
        'countInStock': 10,
        'rating': '4.5',
        'numReviews': 12,
    },
]

